### ISSUE TITLE
Move all static variables, labels and messages into translation file

### ISSUE THREAD

**Issue by ParthivPatel-BTC** [BoTreeConsultingTeam/invoiceme#41]
1) Static variables, labels, messages should be in separate translation file
2) Values should have proper hierarchy.
For e.g.

```
clients:
    captions:
        page_header:
            new: 'New Client'
            edit: 'Edit Client'
   messages:
       created: 'New client created successfully.'
       updated: 'Client updated successfully.'
common:
    button:
        save: 'Save'
        cancel: 'Cancel"
```
